# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1801d13d09ccce40f14ed457c023a1272c000a9766363d786547f5d4b598ace64f5f212ac0484670d81eba2111c88ffe27fa238a3779ae8347992090e0e9b90c

test:
  secret_key_base: 3ef059adf306414e494c70996139ef825cf9e047d14497faed9ee9a18f06618ba027dc636f843be93bf02061c8853fff1bb5a4aaa687ef76b0f1e920834a25ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
